repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
      exclude: "tests/data/*"
    - id: check-yaml
    - id: check-toml

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.7.2
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
